config/routes.rb
Rails.application.routes.draw do

  resources :businesses
  resources :professionals
  resources :residentials
  devise_for :admins, path: 'admins'
  devise_for :users, path: 'users'
  root 'homes#index'
  resources :homes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/residential.rb
class Residential < ApplicationRecord
  belongs_to :user
end

app/controllers/residentials_controller.rb
class ResidentialsController < ApplicationController
  before_action :set_residential, only: [:show, :edit, :update, :destroy]

  # GET /residentials
  # GET /residentials.json
  def index
    @residentials = Residential.all
  end

  # GET /residentials/1
  # GET /residentials/1.json
  def show
  end

  # GET /residentials/new
  def new
    @residential = Residential.new
  end

  # GET /residentials/1/edit
  def edit
  end

  # POST /residentials
  # POST /residentials.json
  def create
    @residential = Residential.new(residential_params)

    respond_to do |format|
      if @residential.save
        format.html { redirect_to @residential, notice: 'Residential was successfully created.' }
        format.json { render :show, status: :created, location: @residential }
      else
        format.html { render :new }
        format.json { render json: @residential.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residentials/1
  # PATCH/PUT /residentials/1.json
  def update
    respond_to do |format|
      if @residential.update(residential_params)
        format.html { redirect_to @residential, notice: 'Residential was successfully updated.' }
        format.json { render :show, status: :ok, location: @residential }
      else
        format.html { render :edit }
        format.json { render json: @residential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residentials/1
  # DELETE /residentials/1.json
  def destroy
    @residential.destroy
    respond_to do |format|
      format.html { redirect_to residentials_url, notice: 'Residential was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residential
      @residential = Residential.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def residential_params
      params.require(:residential).permit(:first_name, :last_name, :gender, :skype, :whatsapp, :user_id)
    end
end

app/helpers/residentials_helper.rb
module ResidentialsHelper
end

app/views/residentials/_form.html.erb
<div class="container" style="padding-top: 20px;">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 no-pad-xs">
      <div class="row login_signup_heading" style="padding:0px;margin:0px;">
        <div class="col-md-12">
          <center><h3 class="heading_text">Create Residential Profile</h3></center>
        </div>
      </div>
      <div class="jumbotron" style="padding-top:1em;padding-bottom:1em; background-color: rgba(48,110,255,0.4); border-radius:0 0 1em 1em;">
        <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10 login_signup_panel">
          <%= form_with(model: residential, local: true) do |form| %>
            <% if residential.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(residential.errors.count, "error") %> prohibited this residential from being saved:</h2>

                <ul>
                <% residential.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
              <%= form.label :first_name %>
              <%= form.text_field :first_name, id: :residential_first_name %>
            </div>

            <div class="field">
              <%= form.label :last_name %>
              <%= form.text_field :last_name, id: :residential_last_name %>
            </div>

            <div class="field">
              <%= form.label :gender %>
              <%= form.text_field :gender, id: :residential_gender %>
            </div>

            <div class="field">
              <%= form.label :skype %>
              <%= form.text_field :skype, id: :residential_skype %>
            </div>

            <div class="field">
              <%= form.label :whatsapp %>
              <%= form.text_field :whatsapp, id: :residential_whatsapp %>
            </div>

            <div class="field">
              <%= form.label :user_id %>
              <%= form.text_field :user_id, id: :residential_user_id %>
            </div>

            <div class="actions">
              <%= form.submit %>
            </div>
          <% end %>
          </div>
          <div class="col-md-1"></div>
        </div>
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/residentials/edit.html.erb
<h1>Editing Residential</h1>

<%= render 'form', residential: @residential %>

<%= link_to 'Show', @residential %> |
<%= link_to 'Back', residentials_path %>

app/views/residentials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Residentials</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Skype</th>
      <th>Whatsapp</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @residentials.each do |residential| %>
      <tr>
        <td><%= residential.first_name %></td>
        <td><%= residential.last_name %></td>
        <td><%= residential.gender %></td>
        <td><%= residential.skype %></td>
        <td><%= residential.whatsapp %></td>
        <td><%= residential.user %></td>
        <td><%= link_to 'Show', residential %></td>
        <td><%= link_to 'Edit', edit_residential_path(residential) %></td>
        <td><%= link_to 'Destroy', residential, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Residential', new_residential_path %>

app/views/residentials/new.html.erb
<% content_for :title, "Create Profile | Info Fiji" %>
<%= render 'form', residential: @residential %>

app/views/residentials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @residential.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @residential.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @residential.gender %>
</p>

<p>
  <strong>Skype:</strong>
  <%= @residential.skype %>
</p>

<p>
  <strong>Whatsapp:</strong>
  <%= @residential.whatsapp %>
</p>

<p>
  <strong>User:</strong>
  <%= @residential.user %>
</p>

<%= link_to 'Edit', edit_residential_path(@residential) %> |
<%= link_to 'Back', residentials_path %>