config/routes.rb
Rails.application.routes.draw do

  resources :businesses
  resources :professionals
  resources :residentials
  devise_for :admins, path: 'admins'
  devise_for :users, path: 'users'
  root 'homes#index'
  resources :homes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/professional.rb
class Professional < ApplicationRecord
  belongs_to :user
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  before_action :set_professional, only: [:show, :edit, :update, :destroy]

  # GET /professionals
  # GET /professionals.json
  def index
    @professionals = Professional.all
  end

  # GET /professionals/1
  # GET /professionals/1.json
  def show
  end

  # GET /professionals/new
  def new
    @professional = Professional.new
  end

  # GET /professionals/1/edit
  def edit
  end

  # POST /professionals
  # POST /professionals.json
  def create
    @professional = Professional.new(professional_params)

    respond_to do |format|
      if @professional.save
        format.html { redirect_to @professional, notice: 'Professional was successfully created.' }
        format.json { render :show, status: :created, location: @professional }
      else
        format.html { render :new }
        format.json { render json: @professional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professionals/1
  # PATCH/PUT /professionals/1.json
  def update
    respond_to do |format|
      if @professional.update(professional_params)
        format.html { redirect_to @professional, notice: 'Professional was successfully updated.' }
        format.json { render :show, status: :ok, location: @professional }
      else
        format.html { render :edit }
        format.json { render json: @professional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professionals/1
  # DELETE /professionals/1.json
  def destroy
    @professional.destroy
    respond_to do |format|
      format.html { redirect_to professionals_url, notice: 'Professional was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professional
      @professional = Professional.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professional_params
      params.require(:professional).permit(:first_name, :last_name, :gender, :skype, :whatsapp, :about, :user_id)
    end
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/views/professionals/_form.html.erb
<%= form_with(model: professional, local: true) do |form| %>
  <% if professional.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professional.errors.count, "error") %> prohibited this professional from being saved:</h2>

      <ul>
      <% professional.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :professional_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :professional_last_name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender, id: :professional_gender %>
  </div>

  <div class="field">
    <%= form.label :skype %>
    <%= form.text_field :skype, id: :professional_skype %>
  </div>

  <div class="field">
    <%= form.label :whatsapp %>
    <%= form.text_field :whatsapp, id: :professional_whatsapp %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_field :about, id: :professional_about %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :professional_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professionals/edit.html.erb
<h1>Editing Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Show', @professional %> |
<%= link_to 'Back', professionals_path %>

app/views/professionals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professionals</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Skype</th>
      <th>Whatsapp</th>
      <th>About</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professionals.each do |professional| %>
      <tr>
        <td><%= professional.first_name %></td>
        <td><%= professional.last_name %></td>
        <td><%= professional.gender %></td>
        <td><%= professional.skype %></td>
        <td><%= professional.whatsapp %></td>
        <td><%= professional.about %></td>
        <td><%= professional.user %></td>
        <td><%= link_to 'Show', professional %></td>
        <td><%= link_to 'Edit', edit_professional_path(professional) %></td>
        <td><%= link_to 'Destroy', professional, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professional', new_professional_path %>

app/views/professionals/new.html.erb
<h1>New Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Back', professionals_path %>

app/views/professionals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @professional.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @professional.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @professional.gender %>
</p>

<p>
  <strong>Skype:</strong>
  <%= @professional.skype %>
</p>

<p>
  <strong>Whatsapp:</strong>
  <%= @professional.whatsapp %>
</p>

<p>
  <strong>About:</strong>
  <%= @professional.about %>
</p>

<p>
  <strong>User:</strong>
  <%= @professional.user %>
</p>

<%= link_to 'Edit', edit_professional_path(@professional) %> |
<%= link_to 'Back', professionals_path %>